//头部
const touli = [
    {title:'免费课程',objectID:'1'},
    {title:'实战课程',objectID:'2'},
    {title:'就业班',icn:'icn-new',objectID:'3'},
    {title:'专栏',objectID:'4'},
    {title:'猿问',objectID:'5'},
    {title:'手记',objectID:'6'},
];
//轮播图
const lunbo =[
    {
        cardlist:[
            {
                hides:'a',
                title:'前沿技术',
                content: [
                    '微服务', '区块链', '以太坊', '机器学习', '深度学习', '计算机视觉', '数据分析＆挖掘',
                ],
                card:[
                    {
                        title: 'OpenCV+TensorFlow 入门人工智能图像处理',
                        img:'bb1.jpg',
                        price:'￥299.0',
                        dot1:'·',
                        info:'中级',
                        dot2:'·',
                        path:'670',
                        objectID:'1',
                    },
                    {
                        title: '区块链技术核心概念与原理讲解',
                        img:'bb2.jpg',
                        info: '入门',
                        dot2: '·',
                        path: '44632',
                        objectID: '2',
                    },
                    {
                        title: '深度学习之目标检测常用算法原理+实践精讲',
                        img:'bb3.jpg',
                        price:'￥499.0',
                        dot1:'·',
                        info:'高级',
                        dot2:'·',
                        path:'350',
                        objectID:'3',
                    },
                    {
                        title: 'Python人工智能常用库Numpy使用入门',
                        img:'bb4.jpg',
                        info:'初级',
                        dot2:'·',
                        path:'29865',
                        objectID:'4',
                    },],
            },
            {
                hides:'b',
                title:'前端开发',
                content:['HTML/CSS','JavaScript','Vue.js','React.JS', 'Angular','Node.js','JQuery','Bootstrap','Sass/Less',
                    'WebApp','小程序','前端工具','CSS','Html5','CSS3',],
                card:[{
                    title: '前端零基础入门',
                    img:'bb21.jpg',
                    price:'￥699.0',
                    dot1:'·',
                    info:' 6步/42课',
                    dot2:'·',
                    path:'2145',
                    objectID:'1',
                },
                    {
                        title: '微信小程序入门与实战 常用组件API开发技巧项目实战',
                        img:'bb22.jpg',
                        price:'￥149.0',
                        dot1:'·',
                        info: '初级',
                        dot2: '·',
                        path: '18371',
                        objectID: '2',
                    },
                    {
                        title: 'Vue核心技术Vue+Vue-Router+Vuex+SSR实战精讲',
                        img:'bb23.jpg',
                        price:'￥366.0',
                        dot1:'·',
                        info:'高级',
                        dot2:'·',
                        path:'2074',
                        objectID:'3',
                    },
                    {
                        title: 'Vue2.5开发去哪儿网App 从零基础入门到实战项目',
                        img:'bb24.jpg',
                        price:'￥266.0',
                        dot1:'·',
                        info:'中级',
                        dot2:'·',
                        path:'2398',
                        objectID:'4',
                    },],
            },
            {
                hides:'c',
                title:'后端开发',
                content:['Java','SpingBoot','Spring Cloud','Python','爬虫',
                    'Django','Tornado','Go','PHP','C','C++','C#','Ruby',],
                card:[
                    {
                        title: 'Java 零基础入门',
                        img:'bb31.jpg',
                        price:'￥568.0',
                        dot1:'·',
                        info:' 3步/28课',
                        dot2:'·',
                        path:'1537',
                        objectID:'1',
                    },
                    {
                        title: 'Spring Boot2.0深度实践之核心技术篇',
                        img:'bb32.jpg',
                        price:'￥366.0',
                        dot1:'·',
                        info: '高级',
                        dot2: '·',
                        path: '1815',
                        objectID: '2',
                    },
                    {
                        title: 'Socket网络编程进阶与实战',
                        img:'bb33.jpg',
                        price:'￥348.0',
                        dot1:'·',
                        info:'中级',
                        dot2:'·',
                        path:'1398',
                        objectID:'3',
                    },
                    {
                        title: 'Java设计模式精讲  Debug方式+内存分析',
                        img:'bb34.jpg',
                        price:'￥299.0',
                        dot1:'·',
                        info:'中级',
                        dot2:'·',
                        path:'1816',
                        objectID:'4',
                    },
                ],
            },
            {
                hides:'d',
                title:'移动开发',
                content:['Android','iSO','React native','WEEX',],
                card:[
                    {
                        title: 'Android 零基础入门',
                        img:'bb41.jpg',
                        price:'￥699.0',
                        dot1:'·',
                        info:' 5步/40课',
                        dot2:'·',
                        path:'499',
                        objectID:'1',
                    },
                    {
                        title: '新版React Native+Redux打造高质量上线App',
                        img:'bb42.jpg',
                        price:'￥399.0',
                        dot1:'·',
                        info: '中级',
                        dot2: '·',
                        path: '1062',
                        objectID: '2',
                    },
                    {
                        title: 'Flutter从入门到进阶 实战携程网App',
                        img:'bb43.jpg',
                        price:'￥348.0',
                        dot1:'·',
                        info:'中级',
                        dot2:'·',
                        path:'1512',
                        objectID:'3',
                    },
                    {
                        title: 'JTop团队大牛带你玩转Android性能分析与优化',
                        img:'bb44.jpg',
                        price:'￥288.0',
                        dot1:'·',
                        info:'高级',
                        dot2:'·',
                        path:'590',
                        objectID:'4',
                    },
                ],
            },
            {
                hides:'e',
                title:'计算机基础',
                content:['计算机网络','算法与数据结构','数学',],
                titles:'云计算&大数据',
                contents:['大数据','Hadoop','Spark','Hbase','Storm', '云计算','AWS','Docker','Kubernetes',],
                card:[
                    {
                        title: 'BAT大牛亲授 个性化推荐算法实战',
                        img:'bb51.jpg',
                        price:'￥399.0',
                        dot1:'·',
                        info:'中级',
                        dot2:'·',
                        path:'423',
                        objectID:'1',
                    },
                    {
                        title: '轻松愉快之玩转SpringData',
                        img:'bb52.jpg',
                        info: '中级',
                        dot2: '·',
                        path: '29684',
                        objectID: '2',
                    },
                    {
                        title: '高等数学-学习算法/人工智能/大数据的第一步',
                        img:'bb53.jpg',
                        price:'￥266.0',
                        dot1:'·',
                        info:'初级',
                        dot2:'·',
                        path:'920',
                        objectID:'3',
                    },
                    {
                        title: 'HBase入门',
                        img:'bb54.jpg',
                        info:'初级',
                        dot2:'·',
                        path:'24321',
                        objectID:'4',
                    },
                ],
            },
            {
                hides:'f',
                title:'运维&测试',
                content:['运维','自动化运维','运维工具','中间件','Linux','测试','功能测试',
                    '性能测试','自动化测试','接口测试','安全测试',],
                titles:'数据库',
                contents:['MySQL','Redis','MongoDB','Oracle','SQL Server','NoSql',],
                card:[{
                    title: '一站式学习Redis  从入门到高可用分布式实践',
                    img:'bb61.jpg',
                    price:'￥348.0',
                    dot1:'·',
                    info:'中级',
                    dot2:'·',
                    path:'1367',
                    objectID:'1',
                },
                    {
                        title: '使用java构建和维护接口自动化测试框架',
                        img:'bb62.jpg',
                        info: '中级',
                        dot2: '·',
                        path: '22526',
                        objectID: '2',
                    },],
            },
            {
                hides:'g',
                title:'UI设计&多媒体',
                content:['模型制作','动效动画','设计基础','设计工具','APPUI设计','产品交互'],
                titles:'游戏',
                contents:['Unity 3D','Cocos2d',],
                card:[
                    {
                        title: '产品交互设计快速入门与实战',
                        img:'bb71.jpg',
                        price:'￥199.0',
                        dot1:'·',
                        info:'初级',
                        dot2:'·',
                        path:'625',
                        objectID:'1',
                    },
                    {
                        title: '高薪设计师必修课 AE移动UI动效设计从入门到实战',
                        img:'bb72.jpg',
                        price:'￥199.0',
                        dot1:'·',
                        info: '中级',
                        dot2: '·',
                        path: '282',
                        objectID: '2',
                    },
                    {
                        title: 'Axure入门初体验',
                        img:'bb73.jpg',
                        info:'入门',
                        dot2:'·',
                        path:'62497',
                        objectID:'3',
                    },
                    {
                        title: '前端工程师必备的PS技能——切图篇',
                        img:'bb74.jpg',
                        info: '初级',
                        dot2: '·',
                        path: '252494',
                        objectID: '4',
                    },
                ],
            },
        ],
        cebian:[
            {name:'aa',group:'前沿 / 区块链 / 人工智能',objectID:'1'},
            {name:'ab',group:'前端 / 小程序 / JS',objectID:'2'},
            {name:'ac',group:'后端 / JAVA / Python',objectID:'3'},
            {name:'ad',group:'移动 / Android / iSO',objectID:'4'},
            {name:'ae',group:'云计算 / 大数据 / 容器',objectID:'5'},
            {name:'af',group:'运维 / 测试 / 数据库',objectID:'6'},
            {name:'ag',group:'UI设计 / 3D动画 / 游戏',objectID:'7'},
        ],
        photos:[
            {
                tit:[{ljtj:'ljtj-1-1',web:'i-web', tit:'Web前端攻城狮',desc:'从未接触编程也可以学',},
                    {ljtj:'ljtj-1-2',web:'i-java',tit:'Java攻城狮',desc:'综合就业排名第一',},
                    {ljtj:'ljtj-1-3',web:'i-python',tit:'Python攻城狮',desc:'应用领域最为广泛的语言',},
                    {ljtj:'ljtj-1-4',web:'i-android',tit:'Android攻城狮',desc:'移动设备市场份额第一',},
                    {ljtj:'ljtj-1-5',web:'i-fullstack',tit:'大前端',desc:'5G时代热门职业',}],
                myCarousel:[{target:'#myCarousel',slide:'0',name:'active'},
                    {target:'#myCarousel',slide:'1'},
                    {target:'#myCarousel',slide:'2'},
                    {target:'#myCarousel',slide:'3'},
                    {target:'#myCarousel',slide:'4'},
                    {target:'#myCarousel',slide:'5'},
                    {target:'#myCarousel',slide:'6'},],
                photo:[{name:'active',img:'aa01.png'},
                    {img:'aa02.png'},
                    {img:'aa03.jpg'},
                    {name:'active',img:'aa04.png'},
                    {img:'aa05.png'},
                    {img:'aa06.png'},],
            }
        ],
    },
];
//实战推荐
const context = [
    {
        name:['bgfff'],
        zhenhe:[{type: [
                {
                    spanl: 'icon-shizhan-l',
                    span: '实／战／推／荐',
                    spanr: 'icon-shizhan-r',
                }
            ],
            shizhan: [
                {
                    index: 'cc11',
                    new: '升级',
                    image: 'cc11.png',
                    label: 'Java',
                    name: 'cc21',
                    title: '一站式学习Java网络编程 全面理解BIO/NIO/AIO',
                    info1: '实战',
                    info2: '初级',
                    path: '56',
                    star: true,
                    price1: '￥255.00',
                    price2: '￥299.00',
                    tip: '限时优惠',
                    objectID: '1',
                },
                {
                    index: 'cc12',
                    image: 'cc12.jpg',
                    label: 'Node.js',
                    name: 'cc22',
                    title: 'Node.js开发仿知乎服务端 深入理解RESTful API',
                    info1: '实战',
                    info2: '初级',
                    path: '386',
                    star: true,
                    price1: '￥266.00',
                    objectID: '2',
                },
                {
                    index: 'cc13',
                    image: 'cc13.jpg',
                    label: '算法',
                    label1: '算法与数据结构',
                    name: 'cc23',
                    title: '玩转算法系列--图论精讲 面试升职必备（java版）',
                    info1: '实战',
                    info2: '初级',
                    path: '415',
                    star: true,
                    price1: '￥348.00',
                    objectID: '3',
                },
                {
                    index: 'cc14',
                    image: 'cc14.jpg',
                    label: 'React.JS',
                    label1: 'Vue.js',
                    name: 'cc24',
                    title: '前端要学的测试课 从Jest入门到TDD/BDD双实战',
                    info1: '实战',
                    info2: '中级',
                    path: '269',
                    star: true,
                    price1: '￥299.00',
                    objectID: '4',
                },
                {
                    index: 'cc15',
                    image: 'cc15.jpg',
                    label: 'Python',
                    name: 'cc25',
                    title: '全面系统python3入门+进阶 课程小白也能听懂',
                    info1: '实战',
                    info2: '初级',
                    path: '9288',
                    star: true,
                    price1: '￥366.00',
                    objectID: '5',
                },
            ],}],
    },
    {
        name:['bg000'],
        zhenhe:[{type: [
                {
                    spanl: 'icon-new-l',
                    span: '新／上／好／课',
                    spanr: 'icon-new-r',
                }
            ],
            shizhan: [
                {
                    index: 'dd11',
                    image: 'dd11.jpg',
                    label1: 'React.JS',
                    label2: 'Vue.js',
                    name: 'dd21',
                    title: '前端要学的测试课 从Jest入门到TDD/BDD双实战',
                    info1: '实战',
                    info2: '中级',
                    path: '269',
                    star: true,
                    price1: '￥299.00',
                    objectID: '1',
                },
                {
                    index: 'dd12',
                    new: '新课',
                    image: 'dd12.png',
                    label1: 'Java',
                    name: 'dd22',
                    title: 'Java并发编程精讲',
                    info1: '实战',
                    info2: '中级',
                    path: '247',
                    star: true,
                    price1: '￥288.00',
                    price2: '￥348.00',
                    tip: '限时优惠',
                    objectID: '2',
                },
                {
                    index: 'dd13',
                    new: '新课',
                    image: 'dd13.png',
                    label1: 'Node.js',
                    label2: '小程序',
                    name: 'dd23',
                    title: '微信小程序云开发-从0打造云音乐全栈小程序',
                    info1: '实战',
                    info2: '中级',
                    path: '108',
                    star: true,
                    price1: '￥298.00',
                    price2: '￥348.00',
                    tip: '限时优惠',
                    objectID: '3',
                },
                {
                    index: 'dd14',
                    image: 'dd14.jpg',
                    label1: 'Angular',
                    name: 'dd24',
                    title: 'Angular8开发拼多多 webapp 从基础到项目实战',
                    info1: '实战',
                    info2: '中级',
                    path: '353',
                    star: true,
                    price1: '￥199.00',
                    objectID: '4',
                },
                {
                    index: 'dd15',
                    image: 'dd15.jpg',
                    label1: 'Java',
                    label2: '算法与数据结构',
                    name: 'dd25',
                    title: '剑指Java面试-Offer直通车',
                    info1: '实战',
                    info2: '中级',
                    path: '4136',
                    star: true,
                    price1: '￥299.00',
                    objectID: '5',
                },
                {
                    index: 'dd16',
                    new: '新课',
                    image: 'dd16.png',
                    label1: 'iOS',
                    label2: 'Vue.js',
                    name: 'dd26',
                    title: '混合开发入门 主流开发方案 实战京东移动端APP',
                    info1: '实战',
                    info2: '中级',
                    path: '135',
                    star: true,
                    price1: '￥299.00',
                    price2: '￥266.00',
                    tip: '限时优惠',
                    objectID: '6',
                },
                {
                    index: 'dd17',
                    image: 'dd17.jpg',
                    label1: 'Python',
                    name: 'dd27',
                    title: '全面系统pythons入门+进阶课程 小白也能听懂',
                    info1: '实战',
                    info2: '中级',
                    path: '9294',
                    star: true,
                    price1: '￥366.00',
                    objectID: '7',
                },
                {
                    index: 'dd18',
                    image: 'dd18.jpg',
                    label1: 'PHP',
                    name: 'dd28',
                    title: '版本管理工具介绍——git篇',
                    info1: '中级',
                    path: '149440',
                    star: false,
                    price1: '免费',
                    objectID: '8',
                },
                {
                    index: 'dd19',
                    image: 'dd19.jpg',
                    label1: 'Python',
                    label2: '自然语言处理',
                    name: 'dd29',
                    title: 'Python数据预处理（三） - 文本特征向量化',
                    info1: '初级',
                    path: '569',
                    star: true,
                    price1: '免费',
                    objectID: '9',
                },
                {
                    index: 'dd20',
                    image: 'dd20.jpg',
                    label1: '算法',
                    label2: '算法与数据结构',
                    name: 'dd30',
                    title: '玩转算法系列--图论精讲 面试升职必备（java版）',
                    info1: '实战',
                    info2: '中级',
                    path: '415',
                    star: true,
                    price1: '免费',
                    objectID: '10',
                },
            ],}],
    },
    {
        name:['bgfff'],
        zhenhe:[{type: [
                {
                    spanl: 'icon-job-l',
                    span: '新／手／入／门',
                    spanr: 'icon-job-r',
                }
            ],
            toutu: [
                {
                    data: 'ee00.png',
                    title: '站在微信小程序风口，实现职业华丽转身',
                    ellipsis: '入门技能+项目开发，逐步深入学习微信小程序开发',
                    objectID: 0,
                },
                {
                    data: 'ee01.jpg',
                    title: '盘点最主流的前端框架有哪些?',
                    ellipsis: '上万人的选择打消你对主流框架的疑惑',
                    objectID: 1,
                }
            ],
            shizhan: [
                {
                    index: 'dd11',
                    image: 'ee1.jpg',
                    label: 'JAVA攻城狮培养计划',
                    image1: 'ee11.jpg',
                    image2: 'ee111.jpg',
                    name: 'dd21',
                    title: 'Java 零基础入门',
                    info1: '就业班',
                    info2: '3步/28课',
                    path: '1547',
                    price1: '￥568.00',
                    objectID: '1',
                },
                {
                    index: 'dd12',
                    image: 'ee2.jpg',
                    label: 'Web前端攻城狮培养计划',
                    image1: 'ee22.jpg',
                    image2: 'ee222.jpg',
                    name: 'dd22',
                    title: '前端零基础入门',
                    info1: '就业班',
                    info2: '6步／42课',
                    path: '1547',
                    price1: '￥699.00',
                    objectID: '2',
                },
                {
                    index: 'dd13',
                    image: 'ee3.jpg',
                    label: 'PHP攻城狮培养计划',
                    image1: 'ee33.jpg',
                    image2: 'ee333.jpg',
                    name: 'dd23',
                    title: 'PHP小白零基础入门',
                    info1: '就业班',
                    info2: '5步／26课',
                    path: '972',
                    price1: '￥658.00',
                    objectID: '3',
                },
                {
                    index: 'dd14',
                    image: 'e4.jpg',
                    label: 'Python',
                    label1: '爬虫',
                    image1: 'ee4.jpg',
                    image2: 'ee4.jpg',
                    name: 'dd24',
                    title: '玩转算法系列--图论精讲 面试升职必备（java版）',
                    info1: '实战',
                    info2: '中级',
                    path: '415',
                    star: true,
                    price1: '￥399.00',
                    objectID: '4',
                },
                {
                    index: 'dd15',
                    image: 'e5.jpg',
                    label: 'HTML/CSS',
                    label1: '小程序',
                    image1: 'ee4.jpg',
                    image2: 'ee4.jpg',
                    name: 'dd25',
                    title: '商业级支付宝小程序入门与实战',
                    info1: '实战',
                    info2: '中级',
                    path: '246',
                    star: true,
                    price1: '￥299.00',
                    objectID: '5',
                },
                {
                    index: 'dd16',
                    image: 'ee6.jpg',
                    label: 'Python攻城狮培养计划',
                    image1: 'ee66.jpg',
                    image2: 'ee666.jpg',
                    name: 'dd26',
                    title: 'Python零基础入门',
                    info1: '就业班',
                    info2: '5步／23课',
                    path: '1151',
                    price1: '￥666.00',
                    objectID: '6',
                },
                {
                    index: 'dd17',
                    image: 'ee7.jpg',
                    label: 'Android',
                    label1: 'ee4.jpg',
                    image2: 'ee4.jpg',
                    name: 'dd27',
                    title: 'Flutter入门与案例实战',
                    info1: '入门',
                    info2: '',
                    path: '18492',
                    price1: '免费',
                    objectID: '7',
                },
                {
                    index: 'dd18',
                    image: 'ee8.jpg',
                    label: 'Android攻城狮培养计划',
                    image1: 'ee88.jpg',
                    image2: 'ee888.jpg',
                    name: 'dd28',
                    title: 'Android零基础入门',
                    info1: '就业班',
                    info2: '5步／40课',
                    path: '509',
                    price1: '￥699.00',
                    objectID: '8',
                },
                {
                    index: 'dd19',
                    image: 'ee9.jpg',
                    label: '小程序',
                    image1: 'ee4.jpg',
                    image2: 'ee4.jpg',
                    name: 'dd29',
                    title: '轻松入门微信小程序与云开发',
                    info1: '初级',
                    info2: '',
                    path: '25632',
                    price1: '免费',
                    objectID: '9',
                },
                {
                    index: 'dd20',
                    new: '新课',
                    image: 'ee10.png',
                    label: '数学',
                    image1: 'ee4.jpg',
                    image2: 'ee4.jpg',
                    name: 'dd30',
                    title: '专为程序员设计的统计课 彻底学会统计分析',
                    info1: '实战',
                    info2: '中级',
                    path: '178',
                    star: true,
                    price1: '￥226.00',
                    price2: '￥266.00',
                    tip: '限时优惠',
                    objectID: '10',
                },
            ]}],
    },
    {
        name:['bg000'],
        zhenhe:[{type: [
                {
                    spanl: 'icon-skill-l',
                    span: '技／能／提／升',
                    spanr: 'icon-skill-r',
                }
            ],
            toutu: [{
                data: 'ff00.jpg',
                title: 'Vue高级工程师实战之路',
                ellipsis: '从Vue基础语法入门最流行的SSR技术实现，完美学习路线打造快速晋升之路!',
                objectID: 0,
            },
                {
                    data: 'ff01.jpg',
                    title: 'Python开发一站式学习',
                    ellipsis: '从入门到开发，学习 好玩 好用 好未来的Python语言',
                    objectID: 1,
                }],
            shizhan: [{
                index: 'dd11',
                image: 'ff11.png',
                label: 'Go',
                label1: '微服务',
                name: 'dd21',
                title: '仿微信抢红包 Golang实战 多版本抢红包系统',
                info1: '实战',
                info2: '中级',
                path: '200',
                star: true,
                price1: '￥348.00',
                objectID: '1',
            },
                {
                    index: 'dd12',
                    new: '新课',
                    image: 'ff12.jpg',
                    label: 'Android',
                    label1: 'iOS',
                    name: 'dd22',
                    title: '5G时代必备 音视频 WebRTC实时互动直播技...',
                    info1: '实战',
                    info2: '中级',
                    path: '537',
                    star: true,
                    price1: '￥288.00',
                    objectID: '2',
                },
                {
                    index: 'dd13',
                    image: 'ff13.jpg',
                    label: 'Java',
                    label1: 'SpringBoot',
                    name: 'dd23',
                    title: 'Spring Boot 2.0深度实战之系列总览',
                    info1: '高级',
                    info2: '',
                    path: '22669',
                    price1: '免费',
                    objectID: '3',
                },
                {
                    index: 'dd14',
                    image: 'ff14.jpg',
                    label: 'Vue.js',
                    name: 'dd24',
                    title: 'Vue.js源码全方位深入解析',
                    info1: '实战',
                    info2: '高级',
                    path: '2272',
                    star: true,
                    price1: '￥488.00',
                    objectID: '4',
                },
                {
                    index: 'dd15',
                    image: 'ff15.jpg',
                    label: 'Kubernetes',
                    label1: '运维',
                    name: 'dd25',
                    title: '部署落地+业务迁移 玩转k8s进阶与企业级实践技能',
                    info1: '实战',
                    info2: '高级',
                    path: '500',
                    star: true,
                    price1: '￥366.00',
                    objectID: '5',
                },
                {
                    index: 'dd16',
                    image: 'ff16.png',
                    label: 'Go',
                    name: 'dd26',
                    title: 'Go开发短地址服务',
                    info1: '高级',
                    info2: '',
                    path: '764',
                    price1: '免费',
                    objectID: '6',
                },
                {
                    index: 'dd17',
                    image: 'ff17.jpg',
                    label: 'Node.js',
                    label1: 'React.js',
                    name: 'dd27',
                    title: '全栈进阶课程 React16.8+Next.js+Koa...',
                    info1: '实战',
                    info2: '高级',
                    path: '275',
                    star: true,
                    price1: '￥399.00',
                    objectID: '7',
                },
                {
                    index: 'dd18',
                    image: 'ff18.png',
                    label: 'Vue.js',
                    name: 'dd28',
                    title: 'axios在vue中的使用',
                    info1: '中级',
                    info2: '',
                    path: '4455',
                    price1: '免费',
                    objectID: '8',
                },
                {
                    index: 'dd19',
                    image: 'ff19.jpg',
                    label: 'Go',
                    label1: 'Redia',
                    name: 'dd29',
                    title: '高并发/高性能 Go语言开发企业级抽奖项目',
                    info1: '实战',
                    info2: '中级',
                    path: '371',
                    star: true,
                    price1: '￥299.00',
                    objectID: '9',
                },
                {
                    index: 'dd20',
                    image: 'ff20.jpg',
                    label: 'React.JS',
                    name: 'dd30',
                    title: 'React高级教程之高阶组件',
                    info1: '高级',
                    info2: '',
                    path: '8912',
                    price1: '免费',
                    objectID: '10',
                },],}],
    },
    {
        name:['bg000'],
        zhenhe:[{type: [
                {
                    spanl: 'icon-tech-l',
                    span: '前／沿／技／术',
                    spanr: 'icon-tech-r',
                }
            ],
            toutu: [
                {
                    data: 'gg00.jpg',
                    title: '慕课微课',
                    ellipsis: '超值课程最低一元体验',
                    objectID: 0,
                },
                {
                    data: 'gg01.jpg',
                    title: '改变职场命运，修炼全栈工程师的必修课',
                    ellipsis: '练就编程十八般武艺，快速转型全栈开发，做全能型工程师!',
                    objectID: 1,
                }
            ],
            shizhan: [
                {
                    index: 'dd11',
                    image: 'gg11.png',
                    label: 'AWS',
                    label1: 'Docker',
                    name: 'dd21',
                    title: 'AWS summit 2019精华：关于人工智能、应用程序开发、DevOps',
                    info1: '入门',
                    info2: '',
                    path: '404',
                    star: true,
                    price1: '免费',
                    objectID: '1',
                },
                {
                    index: 'dd12',
                    new: '新课',
                    image: 'gg12.jpg',
                    label: 'Java',
                    label1: 'SpringBoot',
                    name: 'dd22',
                    title: '精讲Elastic-job + Quartz实现企业级定时任务',
                    info1: '实战',
                    info2: '中级',
                    path: '129',
                    star: true,
                    price1: '￥348.00',
                    objectID: '2',
                },
                {
                    index: 'dd13',
                    image: 'gg13.jpg',
                    label: 'Java',
                    label1: '',
                    name: 'dd23',
                    title: 'MyBatis-Plus入门',
                    info1: '高级',
                    info2: '',
                    path: '12386',
                    price1: '免费',
                    objectID: '3',
                },
                {
                    index: 'dd14',
                    image: 'gg14.jpg',
                    label: '性能测试',
                    name: 'dd24',
                    title: 'LoadRunner性能测试实战训练营',
                    info1: '实战',
                    info2: '高级',
                    path: '256',
                    star: true,
                    price1: '￥499.00',
                    objectID: '4',
                },
                {
                    index: 'dd15',
                    image: 'gg15.jpg',
                    label: 'JavaScript',
                    label1: '',
                    name: 'dd25',
                    title: '下一代前端开发语言 TypeScript从零重构axios',
                    info1: '实战',
                    info2: '中级',
                    path: '1386',
                    star: true,
                    price1: '￥388.00',
                    objectID: '5',
                },
                {
                    index: 'dd16',
                    image: 'gg16.jpg',
                    label: 'Go',
                    label1: '区块链',
                    name: 'dd26',
                    title: '私有区块链，我们一起GO',
                    info1: '中级',
                    info2: '',
                    path: '15387',
                    price1: '免费',
                    objectID: '6',
                },
                {
                    index: 'dd17',
                    image: 'gg17.jpg',
                    label: 'SpringBoot',
                    label1: 'Spark',
                    name: 'dd27',
                    title: 'Spark Streaming实时流处理项目实战',
                    info1: '实战',
                    info2: '中级',
                    path: '1023',
                    star: true,
                    price1: '￥388.00',
                    objectID: '7',
                },
                {
                    index: 'dd18',
                    image: 'gg18.jpg',
                    label: '深度学习',
                    label1: '计算机视觉',
                    name: 'dd28',
                    title: 'TensorFlow与Flask结合打造手写体数字识别',
                    info1: '中级',
                    info2: '',
                    path: '15272',
                    price1: '免费',
                    objectID: '8',
                },
                {
                    index: 'dd19',
                    image: 'gg19.jpg',
                    label: '大数据',
                    label1: 'Hadoop',
                    name: 'dd29',
                    title: '大数据入门第一课 Hadoop基础知识与电商网站日志数据分析',
                    info1: '实战',
                    info2: '中级',
                    path: '712',
                    star: true,
                    price1: '￥288.00',
                    objectID: '9',
                },
                {
                    index: 'dd20',
                    image: 'gg20.jpg',
                    label: '机器学习',
                    label1: '自然语言处理',
                    name: 'dd30',
                    title: '自然语言处理（NLP）入门与实践',
                    info1: '初级',
                    info2: '',
                    path: '8523',
                    price1: '免费',
                    objectID: '10',
                },
            ],}],
    },
];
//精彩手记
const sjyyw = [
    {
        type:[
            {
                spanl:'icon-art-l',
                span:'精／彩／手／记／及／猿／问' ,
                spanr:'icon-art-r',
            }
        ],
        shouji:[
            {
                wqhggai:[
                    {
                        left:'0px',
                        top:'0px',
                        label:'热门话题',
                        a1:' #【内推第2波】#',
                        a2:'打工奋斗7万落京户VS自主创业牧马城市，如何抉择？',
                        img:'h01.jpg',
                        p1:'"毕业求职？跳槽加薪？纠结滋润加班还是苦练x年自主创业？速速提问互撩，你在撩的极有可能就是你的Boss！激不激动？惊不惊喜？Offer已在这里！你的简历在哪里？Scott老师邮箱：wolf18387@qq.comJeson老师邮箱：jeson@imoocc.com"',
                       a3:'了解详情',
                        span1:'往期回顾',

                        wqhg:[{
                            title1:'#【获奖名单戳查看更多】#',
                            title2:'当我们谈论Java时，我们都谈些什么？',
                            image:'h02.jpg',
                            objectID:0,
                        },
                            {
                                title1:'#【内推第1波】#',
                                title2:'直击BAT面试机会！行业大佬在线答疑',
                                image:'h03.jpg',
                                objectID:1,
                            },
                            {
                                title1:'#【花式填坑】第23期#',
                                title2:'运维进化篇：成为Python DevOps工程师有哪些必备条件？',
                                image:'h04.jpg',
                                objectID:2,
                            },],
                    },
                ],
                sjwz:[{
                    left:'390px',
                    top:'0px',
                    title:'手记文章',
                    a1:'【干货合辑】都2019年下半年了， 抓紧上车 ，今年新热技术都在这里！',
                    image:'h05.jpg',
                    content:'互联网发展迅速，不进步就等于在落后，2019年前半年都要过去了，热门新技术你掌握了吗？ 还不知道该学什么怎么学？ 别担心，小慕给大家整理了一篇各大方向的新技术学习干货，点赞收藏走起！ 前端方向 热门技术：TypeScript、Vue、微信小程序 干货文章： 《从今天开始，拿起 TypeScript 做一个轮子的制造者》 《TypeScript应该怎么学》 《TypeScript入门》 《TypeS...',
                    span1:'浏览 12272',
                    span2:'推荐 95',
                    a2:'阅读全文',
                    objectID:'1',
                },
                    {
                        left:'780px',
                        top:'0px',
                        title:'手记文章',
                        a1:'【前端学习路线】以企业需求为导向,看新手如何系统学前端！',
                        image:'h06.jpg',
                        content:'前端怎样入门？ 这一波良心推荐的【前端学习路线】干货，不谈虚的，直接来谈每个阶段要学习的内容 想入门前端的小伙伴们，那就放马过来吧！     首先，给大家分享一张最新的以 企业岗位需求为导向前端技能点图，如下   根据前端工程师技能点图，我们分为四个阶段： 第一阶段：前端基础 （HTML / CSS / HTML5 / CSS3 / JavaScript ） 干货文章： 初识HTML+CSS 【学...',
                        span1:'浏览 27254',
                        span2:'推荐 243',
                        a2:'阅读全文',
                        objectID:'2',
                    },
                    {
                        left:'780px',
                        top:'378px',
                        title:'手记文章',
                        a1:'【面试技巧系列】找工作、涨薪、跳槽都得来一份',
                        image:'h07.jpg',
                        content:'面试是程序员求职过程中最重要的一步 别以为面试技巧很虚 很多技术不错的人 恰恰输在了面试技巧上 知识点怎么复习、问题如何回答 怎么在面试时避免采坑、惊艳面试官 怎么与HR谈论薪资待遇…… 往往这些问题决定你能否成功应聘。 敲黑板划重点： 以下面试技巧神器你值得拥有！ 大量干货文章袭来预警~ 一、通用篇 干货文章： 聪明人喜欢这样写简历 如何有效地备战面试 【程序员】在面...',
                        span1:'浏览 27294',
                        span2:'推荐 124',
                        a2:'阅读全文',
                        objectID:'3',
                    },
                    {
                        left:'390px',
                        top:'400px',
                        title:'手记文章',
                        a1:'【涨薪秘籍】安卓工程师的进阶实战之路',
                        image:'h08.jpg',
                        content:'Android知识杂乱无章，不知道从哪入手？ 技术更新频繁，学不动了，从业者该何去何从？ 工作多年，年龄上升工资却迟迟不涨，危机感满满，该如何破解？ 是时候该开启你的安卓实战之路啦！涨薪的奥秘都在这里！ 今天小慕给大家带来安卓三个阶段的学习路线，从项目入手，逐步深入的带你理解并掌握Android的核心技术，帮助你成为具备高薪实力的Android开发者，顺利破解职场危机！ 不多说啦，上干货。 第一阶...',
                        span1:'浏览 9366',
                        span2:'推荐 39',
                        a2:'阅读全文',
                        objectID:'4',
                    },
                    {
                        left:'0px',
                        top:'678px',
                        title:'手记文章',
                        a1:'【React学习路线】从零进阶前端核心工程师',
                        image:'h09.jpg',
                        content:'哈喽，良心推荐小慕又来跟大家分享啦，今天分享的是React~ 面向工资编程，前端核心框架、加薪神器React了解一下！ React毫无疑问是前端界主流的框架，而框架本身就是热点，可以说是前端工程师们能力提升、快速晋升高级开发工程师的必备技能。 还不知道如何入门？ 技术提升遇到瓶颈？ 别担心，下面小慕就跟大家详细聊一下React的学习路线，入门到进阶的秘籍都在这里啦！ 第一阶段：React快速入门 ...',
                        span1:'浏览 14707',
                        span2:'推荐 98',
                        a2:'阅读全文',
                        objectID:'5',
                    },
                    {
                        left:'780px',
                        top:'756px',
                        title:'手记文章',
                        a1:'【干货推荐】java工程师从零进阶，大牛带你轻松上路',
                        image:'h10.jpg',
                        content:'java新手不知如何入门？ 经验多却面临上升瓶颈期？ 想进阶高级工程师还差点火候？ 今天这波最实用的java实战之路 以战养兵 为你打通职业发展脉络 沿着Java大牛们的思路， 逐步成长为一名业务与思想同样优秀的Java开发者。 就业、晋升、管理均游刃有余！ 不多说了，上干货！ 阅读指南：本文专为Java开发行业人员设计，分为四个阶段，循序渐进的带你进行SSM框架、SpringBoot框架、微服务...',
                        span1:'浏览 28295',
                        span2:'推荐 157',
                        a2:'阅读全文',
                        objectID:'6',
                    },],
                xgyw:[{
                    left:'390px',
                    top:'801px',
                    title:'相关猿问',
                    a1:'想学习自动化测试，应该具备哪些技能',
                    a2:'共6个回答',
                    objectId:'1',
                },
                    {
                        left:'390px',
                        top:'956px',
                        title:'相关猿问',
                        a1:'【有奖问答】与大咖交流前端JS与框架开发，免费赢取前端图书（11.28-12.4）',
                        p1:'最赞回答',
                        p2:'我觉得不管学习哪门语言，到后面总还是要学习一下规范，程序员的素养必不可少啊！！',
                        a2:'共158个回答',
                        objectId:'2',
                    },
                    {
                        left:'0px',
                        top:'1079px',
                        title:'相关猿问',
                        a1:'【各位猿或者媛，一般几点睡啊。有时忍住头痛看java到很晚，第二天就头痛一整天',
                        p1:'已采纳回答',
                        p2:'没有什么事情是需要熬夜完成的',
                        a2:'共372个回答',
                        objectId:'3',
                    },
                    {
                        left:'780px',
                        top:'1134px',
                        title:'相关猿问',
                        a1:'java好学吗.??pp',
                        p1:'最赞回答',
                        p2:'挺好的！',
                        a2:'共273个回答',
                        objectId:'4',
                    },
                    {
                        left:'390px',
                        top:'1210px',
                        title:'相关猿问',
                        a1:'话说，大家想编程的最初初衷是什么',
                        p1:'最赞回答',
                        p2:'说兴趣的话有没有人打我...',
                        a2:'共500个回答',
                        objectId:'5',
                    },],
            },
        ],
    },
];
//精英讲师
const jyms=[
    {
        type:[{
            spanl:'icon-teacher-l',
            span:'慕／课／精／英／名／师' ,
            spanr:'icon-teacher-r',
        }],
        jinyin:[
            {
                img:'one01.jpg',
                img1:'7七月',
                span1:'全栈工程师',
                p:'十年研发及团队管理经验，对程序员面临的各种问题深有体会；精通Python、Java、Node.js、JavaScript等语言，对Web的基础研发、高并发处理与分布式有非常深入的理解。课程讲解深入浅出，极为擅长培养学生的编程思维。',
                objectID:'1',
            },
            {
                img:'one02.jpg',
                img1:'廖师兄',
                span1:'JAVA开发工程师',
                p:'载着干货的老司机。微服务，分布式架构方面经验丰富。',
                objectID:'2',
            },
            {
                img:'one03.jpg',
                img1:'liuyubobobo',
                span1:'全栈工程师',
                p:'创业者，全栈工程师，持续学习者。对技术开发，产品设计、前后端，ios，html5，智能算法等领域均有接触；拥有多款独立App作品；对一切可编程的东西有浓厚兴趣，对游戏编程格外感兴趣。相信编程改变一切。',
                objectID:'3',
            },
            {
                img:'one04.jpg',
                img1:'慕课官方号',
                span1:'页面重构设计',
                p:'慕课，Massive（大规模）Open（开放）Online（在线）Course（课程）。专注做好IT技能教育的MOOC，符合互联网发展潮流接地气儿的MOOC。我们有更多免费资源，我们只教有用的，我们专心做教育。',
                objectID:'4',
            },
            {
                img:'one05.jpg',
                img1:'Oeasy',
                span1:'页面重构设计',
                p:'他，授课风趣幽默，激情四射，自称屌丝青年，中国传媒大学计算机教师；他，专注于网页制作、平面设计、多媒体等多个领域的软件以及应用的挖掘与创新，热爱分享，是新鲜热门软件和应用的导航标，他就是众粉丝心中的“Oeasy老湿”',
                objectID:'5',
            },
            {
                img:'one06.jpg',
                img1:'Stannum',
                span1:'软件工程师',
                p:'目前在财经界俗称的“大摩”，一家成立于美国纽约的国际金融服务公司-摩根士丹利担任软件工程师和敏捷开发专家。 主攻Event Sourcing架构模式的应用。是一个“只有男同事,没有女同事”的程序媛一枚,先后就职于多家投资银行，负责开发“每一个bug都很贵”的内部交易系统,主导了股票交易执行系统和衍生品交易风险控制系统。',
                objectID:'6',
            },
            {
                img:'one07.jpg',
                img1:'谢成',
                span1:'全栈工程师',
                p:'十年研发工作经验，大型公司任高级项目经理及金牌内训讲师，具有丰富的企业面试经验及带团队的经验，个人主导了多个重大项目的研发工作。在Java、NodeJS、JavaScript、HTML5、CSS3、VueJs、ReactJs、前端工程化、前端架构等方面均有建树。在教学过程中，把工作中所遇到的问题及重点融入到课程体系当中，注重培养学生分析问题及解决问题的能力。',
                objectID:'7',
            },
            {
                img:'one08.jpg',
                img1:'悟空',
                span1:'JAVA开发工程师',
                p:'硕士毕业于世界排名Top 9的慕尼黑工业大学（计算机学科排名），国内毕业于同济大学，成绩专业排名Top 1，获公派留学全额奖学金，现就职于一线明星互联网公司。课程深入浅出、系统全面、通俗易懂、干货满满。讲课时充满热情，声情并，全程无废话，生动有趣。',
                objectID:'8',
            },
            {
                img:'one09.jpg',
                img1:'hyman',
                span1:'移动开发工程师',
                p:'同大千攻城狮般无异，本狮有着巨大的火热的不灭的技术热情，痴迷于Android开发。乐于分享，善于将技术生活化，唯愿与大千男女攻城狮共同进步',
                objectID:'9',
            },
            {
                img:'one10.jpg',
                img1:'LGD_Sunday',
                span1:'全栈工程师',
                p:'6年前端、移动端开发经验，在WEB、Android、IOS领域有独特的见解，统筹过的多个项目用户数已过千万，曾就职国内一线互联网公司，目前成立个人开发工作室。致力于研究大前端技术知识，曾为多家互联网公司培训大前端技术，并受邀参加 Google 中国技术分享会，擅长引导学生从本质到思想再到具体解决方案过渡。',
                objectID:'10',
            },
        ],
    }
]
//吊炸天全明星
const dzt =[
    {
        type:[
            {
                spanl:'icon-star-l',
                span:'吊／炸／天／全／明／星',
                spanr:'icon-star-r',
            }
        ],
        lead:[
            {
                image:'k01.jpg',
                p1:'小星星醒醒',
                p2:'风骚课堂学霸',
                objectID:'0',
            },
            {
                image:'k02.jpg',
                p1:'ibeautiful',
                p2:'智慧文章王者',
                objectID:'1',
            },
            {
                image:'k03.png',
                p1:'we1231',
                p2:'慕课第一土豪',
                objectID:'2',
            },
        ],
        other:[
            {
                dd:'purple',
                image:'k01.jpg',
                im:'im1',
                ab:'ab1',
                p1:'="风骚课程学霸"=',
                p2:'小星星醒醒',
                p3:'一周获得 66积分',
                cur:'◆',
                objectID:'1',
            },
            {
                dd:'blue',
                image:'k04.jpg',
                im:'im2',
                ab:'ab2',
                p1:'="智慧文章王者"=',
                p2:'萝卜科技',
                p3:'一周发布手记 10 篇',
                cur:'◆',
                objectID:'2',
            },
            {
                dd:'purple',
                image:'k05.jpg',
                im:'im3',
                ab:'ab3',
                p1:'="风骚课程学霸"=',
                p2:'悬崖上的金魚姬',
                p3:'一周获得 69积分',
                cur:'◆',
                objectID:'3',
            },
            {
                dd:'blue',
                image:'k06.jpg',
                im:'im4',
                ab:'ab4',
                p1:'="智慧文章王者"=',
                p2:'黄小斜',
                p3:'一周发布手记 34 篇',
                cur:'◆',
                objectID:'4',
            },
            {
                dd:'purple',
                image:'k07.jpg',
                im:'im5',
                ab:'ab5',
                p1:'="风骚课程学霸"=',
                p2:'好帮手慕酷酷',
                p3:'一周获得 66积分',
                cur:'◆',
                objectID:'5',
            },
            {
                dd:'purple',
                image:'k08.jpg',
                im:'im6',
                ab:'ab6',
                p1:'="风骚课程学霸"=',
                p2:'梨不开的桃子',
                p3:'一周获得 78积分',
                cur:'◆',
                objectID:'6',
            },
            {
                dd:'purple',
                image:'k09.jpg',
                im:'im7',
                ab:'ab7',
                p1:'="风骚课程学霸"=',
                p2:'时间_记录昨天',
                p3:'一周获得 63积分',
                cur:'◆',
                objectID:'7',
            },
            {
                dd:'purple',
                image:'k10.jpg',
                im:'im8',
                ab:'ab8',
                p1:'="风骚课程学霸"=',
                p2:'妹妹的姐姐',
                p3:'一周获得 75积分',
                cur:'◆',
                objectID:'8',
            },
            {
                dd:'purple',
                image:'k11.jpg',
                im:'im9',
                ab:'ab9',
                p1:'="风骚课程学霸"=',
                p2:'追彩虹的小狐狸',
                p3:'一周获得 72积分',
                cur:'◆',
                objectID:'9',
            },
            {
                dd:'blue',
                image:'k12.jpg',
                im:'im10',
                ab:'ab10',
                p1:'="智慧文章王者"=',
                p2:'python学长',
                p3:'一周发布手记 13 篇',
                cur:'◆',
                objectID:'10',
            },
            {
                dd:'blue',
                dd1:'marr',
                image:'k13.jpg',
                im:'im11',
                ab:'ab11',
                p1:'="智慧文章王者"=',
                p2:'ITMISS',
                p3:'一周发布手记 62 篇',
                cur:'◆',
                objectID:'11',
            },
            {
                dd:'blue',
                dd1:'marl',
                image:'k14.jpg',
                im:'im12',
                ab:'ab12',
                p1:'="智慧文章王者"=',
                p2:'www说',
                p3:'一周发布手记 54 篇',
                cur:'◆',
                objectID:'12',
            },
            {
                dd:'blue',
                image:'k15.jpg',
                im:'im13',
                ab:'ab13',
                p1:'="智慧文章王者"=',
                p2:'慕课网官方_运营中心',
                p3:'一周发布手记 10 篇',
                cur:'◆',
                objectID:'13',
            },
            {
                dd:'blue',
                image:'k16.jpg',
                im:'im14',
                ab:'ab14',
                p1:'="智慧文章王者"=',
                p2:'木易杨说',
                p3:'一周发布手记 15 篇',
                cur:'◆',
                objectID:'14',
            },
        ],
    },
];
//底部
const footer =[
    {
        link:['企业合作','人才招聘','联系我们','讲师招募','帮助中心','意见反馈','慕课大学','代码托管','友情链接'],
        weibo:[{
            gzh:'官方公众号',
            xlwb:'新浪微博',
            sty:'none',
        }],
    },
];
//回到顶部
const fanhui = [
    {
        yijian:'意见反馈',
        yaoqin:'邀请有奖',
        bangzhu:'帮助中心',
        xiazai:'APP下载',
        weix:'官方微信',
        dinbu:'返回顶部',
    }
]
export {touli,lunbo,context,sjyyw,jyms,dzt,footer,fanhui}